#!/usr/bin/env python3
"""
Equation Encoder -- Build-time XOR encryption for free-tier RVA offsets.

Uses the PROLOGUE_DIGEST (from offset_encoder.py) as the fingerprint input
to mixHash() with 4 Pastebin coefficients, producing equation_seed.
At runtime, getFreeRVA(i) = ENC_FREE_OFFSETS[i] ^ g_equation_seed.

The PROLOGUE_DIGEST is stable across inject_prologues/inject_hash runs
(which only modify .rodata), so no chicken-and-egg CRC problem.

Build pipeline:
    1. Build .so -> 2. equation_encoder.py --compute -> 3. Rebuild .so
    4. inject_prologues.py -> 5. inject_hash.py

Usage:
    python equation_encoder.py --compute                              # Read PROLOGUE_DIGEST, compute seed, patch source
    python equation_encoder.py --generate-coefficients                # Generate 4 random coefficients
    python equation_encoder.py --generate-pastebin <A> <B> <C> <D>   # Output Pastebin content
    python equation_encoder.py --test                                 # Self-test mixHash
    python equation_encoder.py --verify <A> <B> <C> <D>              # Verify offsets decode correctly
"""

import os
import re
import struct
import sys
import zlib
import secrets

# ================================================================
# PATHS
# ================================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
NATIVE_LIB_CPP = os.path.join(
    SCRIPT_DIR, "app", "src", "main", "cpp", "native-lib.cpp"
)
OFFSET_ENCODER_PY = os.path.join(SCRIPT_DIR, "offset_encoder.py")

# ================================================================
# COEFFICIENTS -- update these when rotating.
# Generated by --generate-coefficients, consumed by --compute.
# ================================================================
COEFF_A = 0x94F06D95
COEFF_B = 0x4F091D2E
COEFF_C = 0xC907C40D
COEFF_D = 0x98331A64

# ================================================================
# REAL (plaintext) free-tier offsets -- ground truth.
# Must match the comments in native-lib.cpp.
# Update these when the game version changes.
# ================================================================
REAL_FREE_OFFSETS = [
    0x9AC3DE4,  # [0] SphereCast
    0x9AC7784,  # [1] GetCollider
    0x9A232F0,  # [2] GetGameObject
    0x9A281E8,  # [3] GetLayer
    0x9AC8E3C,  # [4] RbGetPosition
    0x471DE28,  # [5] BallGetNumber
    0x471E2A8,  # [6] BallUpdate (hook)
    0x4724C38,  # [7] CueUpdate (hook)
    0x99CB6C4,  # [8] Camera.Main
    0x99CAC18,  # [9] WorldToScreenPoint
    0x99C9400,  # [10] GetPixelHeight
]

M32 = 0xFFFFFFFF  # 32-bit mask

# ================================================================
# mixHash -- keyed hash finalizer (must match C exactly)
# ================================================================
def mix_hash(h, A, B, C, D):
    """Keyed hash finalizer -- matches the C++ mixHash() exactly."""
    h = (h ^ A) & M32
    h = (h * 0x85EBCA6B) & M32
    h = (h ^ (h >> 13)) & M32
    h = (h + B) & M32
    h = (h * 0xC2B2AE35) & M32
    h = (h ^ (h >> 16)) & M32
    h = (h ^ C) & M32
    h = (((h << 7) | (h >> 25)) & M32)  # rotate left 7
    h = (h + D) & M32
    h = (h ^ (h >> 11)) & M32
    return h


# ================================================================
# Read PROLOGUE_DIGEST from offset_encoder.py
# ================================================================
def read_prologue_digest():
    """Parse PROLOGUE_DIGEST from offset_encoder.py."""
    with open(OFFSET_ENCODER_PY, "r", encoding="utf-8") as f:
        for line in f:
            m = re.match(r'^\s*PROLOGUE_DIGEST\s*=\s*(0x[0-9A-Fa-f]+)', line)
            if m:
                return int(m.group(1), 16)
    print("Error: PROLOGUE_DIGEST not found in offset_encoder.py")
    sys.exit(1)


# ================================================================
# Source patching
# ================================================================
def patch_source(equation_seed):
    """
    Patch ENC_FREE_OFFSETS[] in native-lib.cpp with XOR-encoded values.
    Looks for EQUATION_ENCODER_MARKER_START / EQUATION_ENCODER_MARKER_END.
    """
    with open(NATIVE_LIB_CPP, "r", encoding="utf-8") as f:
        source = f.read()

    # Find the marker region
    start_marker = "// EQUATION_ENCODER_MARKER_START"
    end_marker = "// EQUATION_ENCODER_MARKER_END"

    start_idx = source.find(start_marker)
    end_idx = source.find(end_marker)

    if start_idx < 0 or end_idx < 0:
        print("Error: EQUATION_ENCODER_MARKER_START/END not found in native-lib.cpp")
        sys.exit(1)

    # Compute encoded offsets
    encoded = [r ^ equation_seed for r in REAL_FREE_OFFSETS]

    # Build replacement array content
    labels = [
        "SphereCast", "GetCollider", "GetGameObject", "GetLayer",
        "RbGetPosition", "BallGetNumber", "BallUpdate (hook)",
        "CueUpdate (hook)", "Camera.Main", "WorldToScreenPoint",
        "GetPixelHeight",
    ]

    lines = [start_marker]
    lines.append("static const uintptr_t ENC_FREE_OFFSETS[FREE_OFFSET_COUNT] = {")
    for i, (enc, label) in enumerate(zip(encoded, labels)):
        comma = "," if i < len(encoded) - 1 else ""
        lines.append(f"    0x{enc:08X}{comma}  // [{i}] {label}")
    lines.append("};")
    lines.append(end_marker)

    # Replace the region
    before = source[:start_idx]
    after = source[end_idx + len(end_marker):]
    new_source = before + "\r\n".join(lines) + after

    with open(NATIVE_LIB_CPP, "w", encoding="utf-8") as f:
        f.write(new_source)

    print(f"  Patched {len(encoded)} offsets in native-lib.cpp")
    for i, (real, enc, label) in enumerate(zip(REAL_FREE_OFFSETS, encoded, labels)):
        print(f"    [{i:2d}] {label:25s}  0x{real:08X} -> 0x{enc:08X}")


# ================================================================
# Commands
# ================================================================
def cmd_compute():
    """Main build command: read PROLOGUE_DIGEST, derive seed, patch source."""
    print(f"=== Equation Encoder: --compute ===")

    digest = read_prologue_digest()
    print(f"  PROLOGUE_DIGEST: 0x{digest:08X}  (from offset_encoder.py)")
    print(f"  Coefficients: A=0x{COEFF_A:08X} B=0x{COEFF_B:08X} C=0x{COEFF_C:08X} D=0x{COEFF_D:08X}")

    seed = mix_hash(digest, COEFF_A, COEFF_B, COEFF_C, COEFF_D)
    print(f"  equation_seed: 0x{seed:08X}")
    print()

    patch_source(seed)
    print()
    print(f"  Done. Rebuild the .so, then run inject_prologues + inject_hash.")
    print(f"  Pastebin content: {COEFF_A:08X},{COEFF_B:08X},{COEFF_C:08X},{COEFF_D:08X}")


def cmd_generate_coefficients():
    """Generate 4 random 32-bit coefficients."""
    print("=== Equation Encoder: --generate-coefficients ===")
    coeffs = [secrets.randbits(32) for _ in range(4)]
    print(f"  A = 0x{coeffs[0]:08X}")
    print(f"  B = 0x{coeffs[1]:08X}")
    print(f"  C = 0x{coeffs[2]:08X}")
    print(f"  D = 0x{coeffs[3]:08X}")
    print()
    print(f"  Pastebin content: {coeffs[0]:08X},{coeffs[1]:08X},{coeffs[2]:08X},{coeffs[3]:08X}")
    print()
    print("  Update COEFF_A/B/C/D in this script, then run --compute.")


def cmd_generate_pastebin(A, B, C, D):
    """Output Pastebin content for given coefficients."""
    print(f"{A:08X},{B:08X},{C:08X},{D:08X}")


def cmd_test():
    """Self-test: verify mixHash outputs match expected values."""
    print("=== Equation Encoder: --test ===")
    tests_passed = 0
    tests_total = 0

    # Test 1: Known input
    tests_total += 1
    result = mix_hash(0x12345678, 0xAAAAAAAA, 0xBBBBBBBB, 0xCCCCCCCC, 0xDDDDDDDD)
    print(f"  Test 1: mixHash(0x12345678, 0xAAAAAAAA, ...) = 0x{result:08X}")
    result2 = mix_hash(0x12345678, 0xAAAAAAAA, 0xBBBBBBBB, 0xCCCCCCCC, 0xDDDDDDDD)
    if result == result2:
        print(f"    PASS (deterministic)")
        tests_passed += 1
    else:
        print(f"    FAIL (non-deterministic: {result:08X} != {result2:08X})")

    # Test 2: Avalanche
    tests_total += 1
    r1 = mix_hash(0x10000000, COEFF_A, COEFF_B, COEFF_C, COEFF_D)
    r2 = mix_hash(0x10000001, COEFF_A, COEFF_B, COEFF_C, COEFF_D)
    diff_bits = bin(r1 ^ r2).count('1')
    print(f"  Test 2: Avalanche -- 1-bit input change flipped {diff_bits}/32 output bits")
    if diff_bits >= 8:
        print(f"    PASS (good avalanche)")
        tests_passed += 1
    else:
        print(f"    FAIL (poor avalanche, only {diff_bits} bits changed)")

    # Test 3: Different coefficients give different results
    tests_total += 1
    r3 = mix_hash(0x12345678, 0x11111111, 0x22222222, 0x33333333, 0x44444444)
    r4 = mix_hash(0x12345678, 0x11111111, 0x22222222, 0x33333333, 0x44444445)
    print(f"  Test 3: Different coeff D -- 0x{r3:08X} vs 0x{r4:08X}")
    if r3 != r4:
        print(f"    PASS (different outputs)")
        tests_passed += 1
    else:
        print(f"    FAIL (same output with different coefficients)")

    # Test 4: XOR round-trip
    tests_total += 1
    seed = mix_hash(0xDEADBEEF, COEFF_A, COEFF_B, COEFF_C, COEFF_D)
    real_offset = 0x9AC3DE4
    encoded = real_offset ^ seed
    decoded = encoded ^ seed
    print(f"  Test 4: XOR round-trip -- 0x{real_offset:08X} -> 0x{encoded:08X} -> 0x{decoded:08X}")
    if decoded == real_offset:
        print(f"    PASS")
        tests_passed += 1
    else:
        print(f"    FAIL")

    # Test 5: Zero seed = passthrough
    tests_total += 1
    for r in REAL_FREE_OFFSETS:
        if (r ^ 0) != r:
            print(f"  Test 5: FAIL -- XOR with 0 should be identity")
            break
    else:
        print(f"  Test 5: Zero seed passthrough -- PASS")
        tests_passed += 1

    # Test 6: Verify with actual PROLOGUE_DIGEST
    tests_total += 1
    try:
        digest = read_prologue_digest()
        seed = mix_hash(digest, COEFF_A, COEFF_B, COEFF_C, COEFF_D)
        print(f"  Test 6: PROLOGUE_DIGEST=0x{digest:08X} -> seed=0x{seed:08X}")
        if seed != 0:
            print(f"    PASS (non-zero seed)")
            tests_passed += 1
        else:
            print(f"    FAIL (zero seed)")
    except SystemExit:
        print(f"    SKIP (offset_encoder.py not found)")
        tests_passed += 1  # don't fail if file missing

    print(f"\n  Results: {tests_passed}/{tests_total} passed")
    return tests_passed == tests_total


def cmd_verify(A, B, C, D):
    """Verify: read PROLOGUE_DIGEST, compute seed, check source offsets."""
    print(f"=== Equation Encoder: --verify ===")
    digest = read_prologue_digest()
    print(f"  PROLOGUE_DIGEST: 0x{digest:08X}")
    seed = mix_hash(digest, A, B, C, D)
    print(f"  equation_seed: 0x{seed:08X}")

    # Read current encoded values from source
    with open(NATIVE_LIB_CPP, "r", encoding="utf-8") as f:
        source = f.read()

    start_marker = "// EQUATION_ENCODER_MARKER_START"
    end_marker = "// EQUATION_ENCODER_MARKER_END"
    start_idx = source.find(start_marker)
    end_idx = source.find(end_marker)

    if start_idx < 0 or end_idx < 0:
        print("  Error: markers not found")
        return False

    region = source[start_idx:end_idx]
    encoded_values = re.findall(r'0x([0-9A-Fa-f]+)', region)

    print(f"\n  Verifying {len(encoded_values)} encoded offsets:")
    all_ok = True
    labels = [
        "SphereCast", "GetCollider", "GetGameObject", "GetLayer",
        "RbGetPosition", "BallGetNumber", "BallUpdate", "CueUpdate",
        "Camera.Main", "W2S", "PixelHeight",
    ]
    for i, (enc_str, real, label) in enumerate(zip(encoded_values, REAL_FREE_OFFSETS, labels)):
        enc = int(enc_str, 16)
        decoded = enc ^ seed
        ok = "OK" if decoded == real else "MISMATCH"
        if decoded != real:
            all_ok = False
        print(f"    [{i:2d}] {label:20s}  enc=0x{enc:08X} ^ 0x{seed:08X} = 0x{decoded:08X}  (expected 0x{real:08X})  {ok}")

    if all_ok:
        print("\n  VERIFIED: all offsets decode correctly")
    else:
        print("\n  FAILED: some offsets do not match")
    return all_ok


# ================================================================
# CLI
# ================================================================
def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    cmd = sys.argv[1]

    if cmd == "--compute":
        cmd_compute()

    elif cmd == "--generate-coefficients":
        cmd_generate_coefficients()

    elif cmd == "--generate-pastebin":
        if len(sys.argv) < 6:
            print("Usage: equation_encoder.py --generate-pastebin <A> <B> <C> <D>")
            sys.exit(1)
        A, B, C, D = [int(x, 16) for x in sys.argv[2:6]]
        cmd_generate_pastebin(A, B, C, D)

    elif cmd == "--test":
        ok = cmd_test()
        sys.exit(0 if ok else 1)

    elif cmd == "--verify":
        if len(sys.argv) < 6:
            print("Usage: equation_encoder.py --verify <A> <B> <C> <D>")
            sys.exit(1)
        A, B, C, D = [int(x, 16) for x in sys.argv[2:6]]
        ok = cmd_verify(A, B, C, D)
        sys.exit(0 if ok else 1)

    else:
        print(f"Unknown command: {cmd}")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
