#!/usr/bin/env python3
"""
inject_prologues.py — Post-build prologue injection for anti-Frida integrity

Run AFTER compiling libsystem.so (and BEFORE inject_hash.py, since this modifies bytes).

How it works:
  1. Reads the linker map file to find the file offsets of critical detection functions
  2. Reads the first 16 bytes (ARM64 prologue) of each function from the .so
  3. XOR-encrypts those prologues with a per-function key
  4. Finds the corresponding PROLOGUE_SLOT markers in the .so and injects the encrypted bytes
  5. At runtime, the C++ verifier decrypts the stored prologues and compares against live memory

The linker map is generated by adding -Wl,-Map=system.map to CMakeLists.txt.
This gives us exact offsets for even static/hidden functions.

Usage:
    python inject_prologues.py                            # uses default paths
    python inject_prologues.py path/to/libsystem.so path/to/system.map
    python inject_prologues.py --verify path/to/libsystem.so path/to/system.map
    python inject_prologues.py --dump-map path/to/system.map   # debug: list all function offsets
"""

import binascii
import hashlib
import struct
import sys
import os
import re

# ─── Configuration ────────────────────────────────────────────────────────

# 16 bytes of prologue per function (4 ARM64 instructions)
PROLOGUE_SIZE = 16

# XOR key for encrypting stored prologues (per-byte, rotated)
# Different from main decryptStr cipher to avoid pattern recognition
PROLOGUE_XOR_KEY = bytes([0x4B, 0xE7, 0x29, 0x8D, 0xA1, 0x56, 0xF3, 0x0C,
                          0x7A, 0xD8, 0x15, 0x63, 0xBC, 0x94, 0x3E, 0xE0])

# Protected function names (must match exactly as they appear in the linker map)
# These are the functions an attacker would want to NOP/hook to disable detection
PROTECTED_FUNCTIONS = [
    "checkProcMaps",
    "checkProcFD",
    "checkThreadNames",
    "checkFridaPort",
    "checkRootIndicators",
    "checkLoadedLibraries",
    "checkMemoryCRC",
    "checkInlineHooks",
]

# Slot markers — each is a unique 8-byte magic sequence.
# The C++ code defines them as: static const uint8_t PROL_SLOT_N_MARKER[8] = {...};
# followed by:                  static uint8_t PROL_SLOT_N_DATA[16] = {0};
#
# We search for each marker in the binary, then write the encrypted prologue
# into the 16 bytes immediately following the marker.
# Generated deterministically from function names via SHA-256 truncation
# so C++ and Python always agree on the markers.
def generate_slot_marker(func_name: str) -> bytes:
    """Generate a unique 8-byte marker for a function name."""
    h = hashlib.sha256(f"PROL_SLOT_{func_name}".encode()).digest()
    return h[:8]

# Pre-compute markers for each function
SLOT_MARKERS = {name: generate_slot_marker(name) for name in PROTECTED_FUNCTIONS}

# Default paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SO = os.path.join(
    SCRIPT_DIR,
    "app", "build", "intermediates", "cxx", "Debug",
    "4n63m5ky", "obj", "arm64-v8a", "libsystem.so"
)
DEFAULT_MAP = os.path.join(
    SCRIPT_DIR,
    "app", "build", "intermediates", "cxx", "Debug",
    "4n63m5ky", "obj", "arm64-v8a", "system.map"
)

# ─── ELF helpers ──────────────────────────────────────────────────────────

def parse_elf_load_segments(data: bytes) -> list:
    """Parse ELF64 LOAD segments to map virtual addresses to file offsets."""
    # Verify ELF magic
    if data[:4] != b'\x7fELF':
        raise ValueError("Not an ELF file")
    
    is_64 = data[4] == 2
    if not is_64:
        raise ValueError("Only ELF64 (ARM64) is supported")
    
    # ELF64 header
    e_phoff = struct.unpack_from('<Q', data, 32)[0]
    e_phentsize = struct.unpack_from('<H', data, 54)[0]
    e_phnum = struct.unpack_from('<H', data, 56)[0]
    
    segments = []
    for i in range(e_phnum):
        off = e_phoff + i * e_phentsize
        p_type = struct.unpack_from('<I', data, off)[0]
        if p_type != 1:  # PT_LOAD
            continue
        p_offset = struct.unpack_from('<Q', data, off + 8)[0]
        p_vaddr = struct.unpack_from('<Q', data, off + 16)[0]
        p_filesz = struct.unpack_from('<Q', data, off + 32)[0]
        p_memsz = struct.unpack_from('<Q', data, off + 40)[0]
        segments.append({
            'vaddr': p_vaddr,
            'offset': p_offset,
            'filesz': p_filesz,
            'memsz': p_memsz,
        })
    
    return segments

def vaddr_to_file_offset(vaddr: int, segments: list) -> int:
    """Convert a virtual address to a file offset using LOAD segments."""
    for seg in segments:
        if seg['vaddr'] <= vaddr < seg['vaddr'] + seg['filesz']:
            return vaddr - seg['vaddr'] + seg['offset']
    raise ValueError(f"Virtual address 0x{vaddr:X} not in any LOAD segment")

# ─── Linker map parsing ──────────────────────────────────────────────────

def parse_linker_map(map_path: str, function_names: list) -> dict:
    """
    Parse an LLD/GNU ld linker map file to find virtual addresses of functions.

    LLD format (Android NDK):
        5d250  5d250  34c  4  CMakeFiles/...native-lib.cpp.o:(.text._ZL13checkProcMapsv)
        5d250  5d250  34c  1          checkProcMaps()

    Returns: {func_name: vaddr} for each function found.
    """
    results = {}

    with open(map_path, 'r', encoding='utf-8', errors='replace') as f:
        lines = f.readlines()

    for line in lines:
        stripped = line.strip()
        for func in function_names:
            if func in results:
                continue
            # LLD: line ends with funcName()
            if stripped.endswith(f'{func}()'):
                addr_match = re.match(r'\s*([0-9a-fA-F]+)\s+', line)
                if addr_match:
                    results[func] = int(addr_match.group(1), 16)

    return results

# ─── Prologue digest (CRC32 of all prologues combined) ────────────────────

def compute_prologue_digest(so_path: str, map_path: str) -> int:
    """
    Compute CRC32 digest of the concatenated raw prologues of all 8 protected functions.
    Returns a 32-bit unsigned integer.
    
    This digest is folded into g_rva_seed at runtime, so offset_encoder.py must
    pre-compensate by XOR'ing the same digest into BUILD_XOR.
    """
    with open(so_path, 'rb') as f:
        data = f.read()
    
    segments = parse_elf_load_segments(data)
    func_addrs = parse_linker_map(map_path, PROTECTED_FUNCTIONS)
    
    if len(func_addrs) != len(PROTECTED_FUNCTIONS):
        missing = [f for f in PROTECTED_FUNCTIONS if f not in func_addrs]
        raise ValueError(f"Missing functions in map: {', '.join(missing)}")
    
    # Concatenate prologues in order
    all_prologues = bytearray()
    for func_name in PROTECTED_FUNCTIONS:
        vaddr = func_addrs[func_name]
        file_offset = vaddr_to_file_offset(vaddr, segments)
        prologue = data[file_offset:file_offset + PROLOGUE_SIZE]
        if len(prologue) < PROLOGUE_SIZE:
            raise ValueError(f"Not enough bytes for {func_name} at 0x{file_offset:X}")
        all_prologues.extend(prologue)
    
    # CRC32 of all 128 bytes (8 functions × 16 bytes)
    return binascii.crc32(bytes(all_prologues)) & 0xFFFFFFFF


# ─── Core logic ───────────────────────────────────────────────────────────

def xor_encrypt_prologue(prologue: bytes) -> bytes:
    """XOR-encrypt a prologue with the rotating key."""
    return bytes(b ^ PROLOGUE_XOR_KEY[i % len(PROLOGUE_XOR_KEY)]
                 for i, b in enumerate(prologue))

def find_slot_in_binary(data: bytes, func_name: str) -> int:
    """Find the PROL_SLOT_X_MARKER in the binary, return offset of data area (after marker)."""
    marker = SLOT_MARKERS[func_name]
    idx = data.find(marker)
    if idx == -1:
        return -1
    # Verify there's space for the prologue data after the marker
    data_offset = idx + len(marker)
    if data_offset + PROLOGUE_SIZE > len(data):
        return -1
    return data_offset

def inject_prologues(so_path: str, map_path: str, verify_only: bool = False) -> bool:
    """Main injection logic."""
    # Read .so
    with open(so_path, 'rb') as f:
        data = bytearray(f.read())
    
    # Parse ELF
    segments = parse_elf_load_segments(bytes(data))
    print(f"  ELF LOAD segments: {len(segments)}")
    for seg in segments:
        print(f"    vaddr=0x{seg['vaddr']:X}  offset=0x{seg['offset']:X}  "
              f"filesz=0x{seg['filesz']:X}")
    
    # Parse linker map
    func_addrs = parse_linker_map(map_path, PROTECTED_FUNCTIONS)
    print(f"\n  Functions found in map: {len(func_addrs)}/{len(PROTECTED_FUNCTIONS)}")
    
    missing = [f for f in PROTECTED_FUNCTIONS if f not in func_addrs]
    if missing:
        print(f"  WARNING: Missing functions: {', '.join(missing)}")
    
    if not func_addrs:
        print("  ERROR: No functions found in linker map!")
        return False
    
    # Process each function
    success_count = 0
    for func_name in PROTECTED_FUNCTIONS:
        if func_name not in func_addrs:
            print(f"\n  [{func_name}] SKIP — not found in map")
            continue
        
        vaddr = func_addrs[func_name]
        try:
            file_offset = vaddr_to_file_offset(vaddr, segments)
        except ValueError as e:
            print(f"\n  [{func_name}] ERROR — {e}")
            continue
        
        # Read prologue bytes from .so
        prologue = bytes(data[file_offset:file_offset + PROLOGUE_SIZE])
        if len(prologue) < PROLOGUE_SIZE:
            print(f"\n  [{func_name}] ERROR — not enough bytes at offset 0x{file_offset:X}")
            continue
        
        # Find the storage slot
        slot_offset = find_slot_in_binary(bytes(data), func_name)
        if slot_offset == -1:
            print(f"\n  [{func_name}] ERROR — slot marker not found in binary")
            print(f"    Expected marker: {SLOT_MARKERS[func_name].hex()}")
            continue
        
        # Encrypt prologue
        encrypted = xor_encrypt_prologue(prologue)
        
        marker_hex = SLOT_MARKERS[func_name].hex()
        print(f"\n  [{func_name}]")
        print(f"    vaddr:      0x{vaddr:X}")
        print(f"    file_off:   0x{file_offset:X}")
        print(f"    prologue:   {prologue.hex()}")
        print(f"    encrypted:  {encrypted.hex()}")
        print(f"    slot_marker: {marker_hex}")
        print(f"    slot_off:   0x{slot_offset:X}")
        
        if verify_only:
            stored = bytes(data[slot_offset:slot_offset + PROLOGUE_SIZE])
            if stored == encrypted:
                print(f"    status:     [OK] matches")
            elif stored == b'\x00' * PROLOGUE_SIZE:
                print(f"    status:     [WARN] not yet injected (all zeros)")
            else:
                print(f"    status:     [FAIL] mismatch")
                print(f"    stored:     {stored.hex()}")
            continue
        
        # Inject
        data[slot_offset:slot_offset + PROLOGUE_SIZE] = encrypted
        print(f"    status:     INJECTED")
        success_count += 1
    
    if verify_only:
        return True
    
    if success_count == 0:
        print("\n  ERROR: No prologues injected!")
        return False
    
    # Save
    with open(so_path, 'wb') as f:
        f.write(data)
    print(f"\n  [OK] {success_count} prologues injected into {os.path.basename(so_path)}")
    
    # Verify round-trip
    with open(so_path, 'rb') as f:
        verify_data = f.read()
    all_ok = True
    for func_name in PROTECTED_FUNCTIONS:
        if func_name not in func_addrs:
            continue
        slot_offset = find_slot_in_binary(verify_data, func_name)
        if slot_offset == -1:
            continue
        vaddr = func_addrs[func_name]
        file_offset = vaddr_to_file_offset(vaddr, segments)
        prologue = verify_data[file_offset:file_offset + PROLOGUE_SIZE]
        encrypted = xor_encrypt_prologue(prologue)
        stored = verify_data[slot_offset:slot_offset + PROLOGUE_SIZE]
        if stored != encrypted:
            print(f"  [FAIL] Round-trip mismatch for {func_name}")
            all_ok = False
    if all_ok:
        print("  [OK] Round-trip verification PASSED")
    
    return all_ok

def dump_map(map_path: str):
    """Debug: dump all functions from the linker map (LLD format)."""
    with open(map_path, 'r', encoding='utf-8', errors='replace') as f:
        lines = f.readlines()

    # LLD format: lines ending with funcName()
    funcs = []
    for line in lines:
        m = re.match(r'\s*([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+\d+\s+(\w+)\(\)\s*$', line)
        if m:
            addr, _, size, name = m.groups()
            funcs.append((name, addr, size))

    print(f"Functions in {os.path.basename(map_path)}:")
    for name, addr, size in sorted(funcs, key=lambda x: int(x[1], 16)):
        star = " <<<" if name in PROTECTED_FUNCTIONS else ""
        print(f"  0x{addr}  size=0x{size}  {name}{star}")
    print(f"\nTotal: {len(funcs)} functions")

def print_cpp_markers():
    """Print the C++ marker declarations to paste into native-lib.cpp."""
    print("// === PROLOGUE INTEGRITY SLOT MARKERS ===")
    print("// Generated by inject_prologues.py — do NOT edit manually.")
    print("// Each marker is followed by 16 zero bytes where the Python script")
    print("// injects the XOR-encrypted prologue of the corresponding function.")
    print()
    for func_name in PROTECTED_FUNCTIONS:
        marker = SLOT_MARKERS[func_name]
        marker_str = ','.join(f'0x{b:02X}' for b in marker)
        print(f'// Prologue slot for {func_name}')
        print(f'static const uint8_t PROL_SLOT_{func_name.upper()}_MARKER[8] = {{{marker_str}}};')
        print(f'static uint8_t PROL_SLOT_{func_name.upper()}_DATA[{PROLOGUE_SIZE}] = {{0}};')
        print()
    
    # Print the XOR key for C++ decryption
    key_str = ','.join(f'0x{b:02X}' for b in PROLOGUE_XOR_KEY)
    print(f'static const uint8_t PROLOGUE_XOR_KEY[{len(PROLOGUE_XOR_KEY)}] = {{{key_str}}};')
    print()
    
    # Print a struct-based lookup table for the verifier
    print("// Prologue verification table")
    print("struct PrologueSlot {")
    print("  void *funcAddr;              // runtime address of the function")
    print("  const uint8_t *storedData;   // pointer to PROL_SLOT_*_DATA (encrypted)")
    print("};")
    print()
    print("// Initialize this in startTrainer() or initMemoryCRC() with actual function pointers:")
    print("// static PrologueSlot g_prologueSlots[] = {")
    for func_name in PROTECTED_FUNCTIONS:
        print(f"//   {{(void*){func_name}, PROL_SLOT_{func_name.upper()}_DATA}},")
    print("// };")

# ─── CLI ──────────────────────────────────────────────────────────────────

def resolve_so_and_map(argv_args: list) -> tuple:
    """Extract .so and .map paths from positional args, with defaults."""
    args = [a for a in argv_args if not a.startswith('--')]
    so_path = args[0] if len(args) > 0 else DEFAULT_SO
    map_path = args[1] if len(args) > 1 else DEFAULT_MAP
    return so_path, map_path


def main():
    if '--generate-cpp' in sys.argv:
        print_cpp_markers()
        return
    
    if '--dump-map' in sys.argv:
        args = [a for a in sys.argv[1:] if a != '--dump-map']
        map_path = args[0] if args else DEFAULT_MAP
        if not os.path.isfile(map_path):
            print(f"ERROR: Map file not found: {map_path}")
            sys.exit(1)
        dump_map(map_path)
        return
    
    # --- Compute prologue digest (CRC32 of all prologues) ---
    if '--compute-digest' in sys.argv:
        so_path, map_path = resolve_so_and_map(sys.argv[1:])
        if not os.path.isfile(so_path):
            print(f"ERROR: .so not found: {so_path}")
            sys.exit(1)
        if not os.path.isfile(map_path):
            print(f"ERROR: map not found: {map_path}")
            sys.exit(1)
        digest = compute_prologue_digest(so_path, map_path)
        print(f"Prologue digest (CRC32): 0x{digest:08X}")
        print(f"  Paste into offset_encoder.py: PROLOGUE_DIGEST = 0x{digest:08X}")
        return
    
    # --- Auto-patch PROLOGUE_DIGEST in offset_encoder.py ---
    if '--update-encoder' in sys.argv:
        so_path, map_path = resolve_so_and_map(sys.argv[1:])
        if not os.path.isfile(so_path):
            print(f"ERROR: .so not found: {so_path}")
            sys.exit(1)
        if not os.path.isfile(map_path):
            print(f"ERROR: map not found: {map_path}")
            sys.exit(1)
        
        digest = compute_prologue_digest(so_path, map_path)
        print(f"Prologue digest: 0x{digest:08X}")
        
        encoder_path = os.path.join(SCRIPT_DIR, 'offset_encoder.py')
        if not os.path.isfile(encoder_path):
            print(f"ERROR: offset_encoder.py not found at {encoder_path}")
            sys.exit(1)
        
        with open(encoder_path, 'r') as f:
            content = f.read()
        
        # Replace PROLOGUE_DIGEST = 0x... with new value
        new_content, count = re.subn(
            r'PROLOGUE_DIGEST\s*=\s*0x[0-9A-Fa-f]+',
            f'PROLOGUE_DIGEST = 0x{digest:08X}',
            content
        )
        
        if count == 0:
            print("ERROR: PROLOGUE_DIGEST not found in offset_encoder.py")
            print("  Add this line: PROLOGUE_DIGEST = 0x00000000")
            sys.exit(1)
        
        with open(encoder_path, 'w') as f:
            f.write(new_content)
        
        print(f"  Updated {encoder_path}")
        print(f"  PROLOGUE_DIGEST = 0x{digest:08X}")
        print(f"  Now re-run: python offset_encoder.py")
        return
    
    verify_only = '--verify' in sys.argv
    so_path, map_path = resolve_so_and_map(sys.argv[1:])
    
    if not os.path.isfile(so_path):
        print(f"ERROR: .so file not found: {so_path}")
        print(f"  Build the project first with: gradlew assembleDebug")
        sys.exit(1)
    
    if not os.path.isfile(map_path):
        print(f"ERROR: Linker map not found: {map_path}")
        print(f"  Add to CMakeLists.txt: target_link_options(${CMAKE_PROJECT_NAME} PRIVATE -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/system.map)")
        sys.exit(1)
    
    action = "Verifying" if verify_only else "Injecting prologues into"
    print(f"{action}: {so_path}")
    print(f"  Map file: {map_path}")
    print(f"  File size: {os.path.getsize(so_path):,} bytes")
    print(f"  Protected functions: {len(PROTECTED_FUNCTIONS)}")
    
    success = inject_prologues(so_path, map_path, verify_only)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
